### ISSUE TITLE
cannot download ver0.8.1

### ISSUE THREAD

**Issue by hrdxwandg** [milvus-io/milvus-sdk-java#107]
i can not download ver0.8.1
![image](https://user-images.githubusercontent.com/2166948/84041624-a421de80-a9d6-11ea-91bd-beeb6bbe7f67.png)

Is anyone have the same problem? how to solve it?

**Comment by sahuang** [comment]
Hi, how did you download the Java SDK? Did you try README method to download with Apache Maven?

**Comment by hrdxwandg** [comment]
follow the README, add dependency in pom.xml
    <dependency>
      <groupId>io.milvus</groupId>
      <artifactId>milvus-sdk-java</artifactId>
      <version>0.8.1</version>
    </dependency>

**Comment by sahuang** [comment]
This should be the correct way, the SDK is also listed in [maven-central](https://search.maven.org/artifact/io.milvus/milvus-sdk-java). 

Maven uses HTTP to download its dependencies along with the dependencies of the Maven project. Therefore, if you failed to download your required dependencies, it’s likely to be caused by your local firewall & HTTP proxy configurations. Maybe try again when your internet is stable.

**Comment by hrdxwandg** [comment]
yep, i close my http proxy, and It's OK。
thx

**Comment by sahuang** [comment]
No problem.
