### ISSUE TITLE
Exception in thread "main" io.milvus.client.ConnectFailedException: Exception occurred: io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact

### ISSUE THREAD

**Issue by ashfaq92** [milvus-io/milvus-sdk-java#115]
When I try to run the following given code to connect to milvus server, I get the exception:

```
ERROR MilvusGrpcClient Connect failed! io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
Failed to connect to Milvus server: io.milvus.client.ConnectFailedException: Exception occurred: io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
```

On the other hand, my milvus server is successfully running in docker container and I can access it using python SDK
![image](https://user-images.githubusercontent.com/28701122/86508988-12f82900-be17-11ea-8f62-a03b719ba9d4.png)

**Comment by sahuang** [comment]
Hi, are you running example codes from /example folder? Did you maven import from pom.xml? 

The exception is not caused by Milvus server. Instead, it is related to java-grpc and it seems to be a [dependency issue](https://github.com/google/java-photoslibrary/issues/9#issuecomment-649906133). Maybe remove `grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact` and reinstall using the pom.xml provided?
