### ISSUE TITLE
the logic in method: isConnect() may cause an unexcepted exception be thrown 

### ISSUE THREAD

**Issue by Alsace-lee** [milvus-io/milvus-sdk-java#117]
There are five states of the channel in the client，but the method: isConnect()  returns true only when the channel state is READY。if a channel is in idle state because of lack of new RPCs, the following code would throw a unexcepted exception: "channel is not shutdown or terminated"

if(!milvusClient.isConnect()){
    milvusClient.connect();
}

**Comment by sahuang** [comment]
This is intentional in the current Java SDK design. The idea is that `isConnect` means client has successfully connected to Milvus server and is now in `READY` mode. 

The definition of [IDLE](https://grpc.github.io/grpc-java/javadoc/io/grpc/ConnectivityState.html) stated in `Enum ConnectivityState` from grpc-java documentation states that "this is the state where the channel is not even trying to create a connection because of a lack of new or pending RPCs". In this case we should assume that `isConnect()` returns false.

There is a unittest for Milvus grpc client:

```java
void idleTest() throws InterruptedException, ConnectFailedException {
    MilvusClient client = new MilvusGrpcClient();
    ConnectParam connectParam =
        new ConnectParam.Builder()
            .withHost("localhost")
            .withIdleTimeout(1, TimeUnit.SECONDS)
            .build();
    client.connect(connectParam);
    TimeUnit.SECONDS.sleep(2);
    // Channel should be idle
    assertFalse(client.isConnected());
    // A new RPC would take the channel out of idle mode
    assertTrue(client.listCollections().ok());
  }
```

I am unsure if Issue #98 is related to the unexpected exception you mentioned: "channel is not shutdown or terminated". If you have a better design or explanation feel free to discuss. Note that we are currently using grpc-java `v1.27.2` and I am considering upgrading it to the latest `v1.30.2` for the next patch.

**Comment by Alsace-lee** [comment]
> This is intentional in the current Java SDK design. The idea is that `isConnect` means client has successfully connected to Milvus server and is now in `READY` mode.
> 
> The definition of [IDLE](https://grpc.github.io/grpc-java/javadoc/io/grpc/ConnectivityState.html) stated in `Enum ConnectivityState` from grpc-java documentation states that "this is the state where the channel is not even trying to create a connection because of a lack of new or pending RPCs". In this case we should assume that `isConnect()` returns false.
> 
> There is a unittest for Milvus grpc client:
> 
> ```java
> void idleTest() throws InterruptedException, ConnectFailedException {
>     MilvusClient client = new MilvusGrpcClient();
>     ConnectParam connectParam =
>         new ConnectParam.Builder()
>             .withHost("localhost")
>             .withIdleTimeout(1, TimeUnit.SECONDS)
>             .build();
>     client.connect(connectParam);
>     TimeUnit.SECONDS.sleep(2);
>     // Channel should be idle
>     assertFalse(client.isConnected());
>     // A new RPC would take the channel out of idle mode
>     assertTrue(client.listCollections().ok());
>   }
> ```
> 
> I am unsure if Issue #98 is related to the unexpected exception you mentioned: "channel is not shutdown or terminated". If you have a better design or explanation feel free to discuss. Note that we are currently using grpc-java `v1.27.2` and I am considering upgrading it to the latest `v1.30.2` for the next patch.

You're right, but I can only realize that is intentional when I have read the source code. In fact, at the beginning, I just wanted to make sure that the current client is available through such a judgment. The exception it throws makes me confused for a while,because literally, there's no problem doing so .

**Comment by sahuang** [comment]
I understand your concerns and thanks for raising such an issue. It is indeed difficult for us to list all design rationales here, and I agree that the exception is a bit confusing. I haven't had a good idea to bypass that exception from SDK level at this moment.

In Javadoc I mentioned that the API will return true if `the client is connected to Milvus server and the channel's connectivity state is READY`. Therefore only client available is not enough.

**Comment by Alsace-lee** [comment]
The core is that the connect state in grpc is a bit different from the connect state we generally understand. 
Since the channel status will become READY after sending a new request and the RPC process will be completed, the difference between READY and IDLE becomes not so important for users, because both can send requests. 
It is recommended to add a method to distinguish it from the isConnect() method to inform users whether it is safe to use the client to send requests

**Comment by sahuang** [comment]
Hi, after further discussions with my fellow engineers, we decided to remove `**isConnect()**` API from the next SDK release. Currently, Milvus Python (and Go) SDK already removed this method. 

The reason is that, according to gRPC documentation, it is not recommended to check whether connectivity is set successfully by `ConnectivityState` (it is an experimental API). Instead, you can just start the server and start sending RPC requests. This will wake up the connection and enable subsequent communications.

We will also add an optional timeout param in all methods. There is no need to check if Milvus server is connected before each API call.

**Comment by sahuang** [comment]
From Milvus 0.10.1 onwards, if you want to use Java SDK, simply establish a connection via operations (e.g. insert/query). isConnect is unnecessary.

**Comment by evandromoura** [comment]
private boolean isMilvusOnline() {
		ExecutorService executor = Executors.newSingleThreadExecutor();
        Callable<Void> task = () -> {
            this.milvusClient.getServerVersion();
            return null;
        };
        Future<Void> future = executor.submit(task);
        try {
            future.get(100, TimeUnit.MILLISECONDS);
        } catch (TimeoutException e) {
            System.out.println("Tempo de execução excedido");
            future.cancel(true);
            return false;
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
            return false;
        } finally {
            executor.shutdownNow();
        }
        return true;
	}
