### ISSUE TITLE
When I restart my server, how can I use old inserted data? 

### ISSUE THREAD

**Issue by kyle-kai** [milvus-io/milvus-sdk-java#119]
When I restart my server, how can I use old inserted data? If i need to insert again, it will cost too long time

**Comment by sahuang** [comment]
The data you previously inserted will be stored in `/tmp/milvus/db`. If you want to get old inserted data, you can check collection name and get vectors from that collection.

**Comment by kyle-kai** [comment]
> /tmp/milvus/db

but, if I run the milvus docker in a mesos docker, when I restarted, the files all gone, how can I solve it, can I use hdfs or other public storage or disk storage

**Comment by kyle-kai** [comment]
> The data you previously inserted will be stored in `/tmp/milvus/db`. If you want to get old inserted data, you can check collection name and get vectors from that collection.

the another question is the path “/tmp/milvus/db” you mentioned , is the path in the docker ? or is the path in the physical server?

**Comment by sahuang** [comment]
When you start the Milvus server, by default all logs, collection db data, and WAL info will be stored under `/tmp/milvus`. If you start server on docker then it is your docker path. Then if you restart docker, since `/tmp` will be gone, you will lose all previous data, and in this case you must re-insert data.

To avoid this problem, I suggest that you change the configurations to let db path point to a path that is accessible for you and will not be deleted. (e.g. you can use -v in docker to put data in your local machine).
