### ISSUE TITLE
关于查询dql限制向量距离问题

### ISSUE THREAD

**Issue by sixgodleaf** [milvus-io/milvus-sdk-java#145]
最新版本dql查询语句中是否可以限制两个向量距离，比如我希望查询向量距离大于0.8的数据才返回数据。

**Comment by sahuang** [comment]
Currently, range filtering is not available in DSL queries. My suggestion is that you filter the records with `Distance > 0.8` after getting the `topK` results (the results are sorted in distance). In this scenario, you might want to lift `topK` a bit in order to get enough results after manual filtering.

**Comment by sixgodleaf** [comment]
谢谢，那后续有计划增加这个功能吗，还有，对于dql的用法，有较详细的文档吗

**Comment by sahuang** [comment]
This is not in our plan and I think won't be added in the foreseeable future.

In terms of DSL usage, you can refer to [Examples](https://github.com/milvus-io/milvus-sdk-java/blob/0.9.1/examples/src/main/java/MilvusBasicExample.java) for more information.

**Comment by sixgodleaf** [comment]
再请教一下，当前新版本增加的属性的查询，对性能影响大吗，这个查询的原理是怎么样的？

**Comment by sahuang** [comment]
属性的查询相比纯向量搜索性能肯定会差一点,因为需要花时间处理属性数据. 但是性能的影响很小,实测可能不到10%.

查询原理概括下来就是先做属性过滤后做向量搜索.

**Comment by sixgodleaf** [comment]
非常感谢
